config/routes.rb
Rails.application.routes.draw do
  devise_for :drivers, path: 'drivers', controllers: {sessions: "drivers/sessions"}

  namespace :admin do
    resources :drivers do
      resources :vehicles, shallow: true
      put :accept
      put :reject
      put :pass
      put :fail
      put :activation
    end
  end

  devise_scope :driver do
    get 'ascending_sort' => 'drivers#ascending_sort'
  end

  devise_for :users, skip: [:registrations],path: 'users', controllers: {sessions: "users/sessions"}
  devise_scope :user do
    resource :users,
             only: [:edit, :update, :destroy],
             controller: 'devise/registrations',
             as: :user_registration do
              get 'cancel'
             end
    get 'user' => "welcome#index"
  end

  resources :organizations, controllers: {registrations: "organizations/registrations"}
  # devise_for :riders, :skip => [:registrations],  path: 'riders', controllers: {sessions: "riders/sessions"}

  resources :riders do
    collection do
      get 'edit/:rider_id' => 'riders#edit'
      post 'bulk_update'
    end
    member do
      get 'locations'
    end
    put :activation
  end
  #
  # devise_scope :rider do
  #   resource :riders_devise,
  #            controller: 'devise/registrations',
  #            as: :rider_registration do
  #             get 'cancel'
  #            end
  #            get 'sort-down' => 'riders#sort_down'
  # end

  mount Api::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"

  get 'welcome/index'
  get 'welcome/welcome'
  get 'welcome/driver'

  get '/privacy_policy' => 'pages#privacy_policy'
  get '/terms_and_conditions' => 'pages#terms_and_conditions'
  get '/support' => 'pages#support'

  resources :rides do
    member do
      put 'cancel' => 'rides#cancel'
    end
  end

  resources :admin_ride do
    member do
      put 'approve' => 'admin_ride#approve'
      get 'review' => 'admin_ride/ride_cancellations#review'
      put 'cancel' => 'admin_ride/ride_cancellations#cancel'
    end
  end

  resources :tokens, path_names: { new: 'new/:rider_id' }

  root 'welcome#welcome'

  namespace :api, :defaults => {:format => :json} do
    as :driver do
      post   "v1/sign-in"       => "v1/sessions#create"
      delete "v1/sign-out"      => "v1/sessions#destroy"
    end
  end

  namespace :user do
    root :to => "welcome#index"
  end

  # namespace :riders do
  #   root :to => "welcome#rider"
  #   resources :tokens
  #
  # end

end

app/controllers/admin_ride/cancellation_reasons_controller.rb
class AdminRide::CancellationReasonsController < ApplicationController
  def review
    @ride = Ride.find(params[:id])
  end

  def cancel
    @ride = Ride.find(params[:id])
    authorize @ride
    if %w[pending approved scheduled].include? @ride.status
      @ride.update_attributes(status: 'canceled', cancellation_reason: params[:ride][:cancellation_reason])
      @ride.token&.update_attribute(:ride_id, nil)
      flash.notice = 'Ride canceled.'
      redirect_to request.referrer || admin_ride_index_path
    end
  end
end

app/controllers/admin_ride/ride_cancellations_controller.rb
class AdminRide::RideCancellationsController < ApplicationController
  def review
    begin
      @ride = Ride.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash.now[:alert] = "Record not found."
      redirect_to admin_ride_index_path
      return
    end
  end

  def cancel
    begin
      @ride = Ride.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash.now[:alert] = "Record not found."
      redirect_to admin_ride_index_path
      return
    end

    if ride_params[:cancellation_reason] == 'Other'
      @cancellation_reason = ride_params[:cancellation_other_reason]
    else
      @cancellation_reason = ride_params[:cancellation_reason]
    end

    if %w[pending approved scheduled].include? @ride.status
      @ride.update_attributes(status: 'canceled', cancellation_reason: @cancellation_reason)
      @ride.token&.update_attribute(:ride_id, nil)
      flash.notice = 'Ride canceled.'
      redirect_to admin_ride_path @ride
    end
  end

  private
    def ride_params
      params.require(:ride).permit(:cancellation_reason, :cancellation_other_reason)
    end
end

app/controllers/admin_ride_controller.rb
# frozen_string_literal: true

class AdminRideController < ApplicationController
  RIDES_PER_PAGE_AMOUNT = 10
  before_action :authenticate_user!
  before_action :conditional_ride_reason, only: [:create, :update]
  #  before_action :rider_is_active, only: :create
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  layout 'administration'

  def new
    @ride = Ride.new
  end

  def show
    begin
    @ride = Ride.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash.now[:alert] = "Record not found."
      redirect_to admin_ride_index_path
      return
    end
    @second_ride = Ride.find(@ride.return) if @ride.return
    authorize @ride
  end

  def index
    if params[:status].present?
      @rides = Ride.status(params[:status]).where("organization_id =? AND pick_up_time >=?", current_user.organization.id, Date.today)
    else
      @rides = Ride.select("rides.*,riders.first_name,riders.last_name").joins(:rider).where("rides.organization_id =? AND pick_up_time >= ?", current_user.organization.id, Date.today)
    end
    @query = @rides.ransack(params[:q])
    @search = Kaminari.paginate_array(@query.result).page(params[:page]).per(RIDES_PER_PAGE_AMOUNT)
  end

  def edit
    begin
    @ride = Ride.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash.now[:alert] = "Record not found."
      redirect_to admin_ride_index_path
      return
    end
    if @ride.outbound
      @ride = Ride.find(@ride.outbound)
    end
    authorize @ride
  end

  def create
    begin
      rider = Rider.find(ride_params[:rider_id])
    rescue ActiveRecord::RecordNotFound
      flash.now[:alert] = "The rider can't be blank."
      @ride = Ride.new
      render 'new'
      return
    end
    authorize rider
    keep_proccessing = rider_is_active
    if !keep_proccessing
      return
    end
    organization = Organization.find(current_user.organization_id)
    if organization.use_tokens == true
      token = rider.next_valid_token
      token = rider.valid_tokens.create if token.nil?
    end
    @start_location = Location.new(street: ride_params[:start_street],
                                   city: ride_params[:start_city],
                                   state: ride_params[:start_state],
                                   zip: ride_params[:start_zip])
    @end_location = Location.new(street: ride_params[:end_street],
                                 city: ride_params[:end_city],
                                 state: ride_params[:end_state],
                                 zip: ride_params[:end_zip])

    @ride = Ride.new(organization_id: current_user.organization_id,
                     rider_id: rider.id,
                     driver_id: ride_params[:driver_id],
                     pick_up_time: ride_params[:pick_up_time],
                     reason: @reason,
                     round_trip: ride_params[:round_trip],
                     notes: ride_params[:notes])
    if @ride.round_trip
      @second_ride = Ride.new(organization_id: current_user.organization_id,
                              rider_id: rider.id,
                              driver_id: ride_params[:second_driver_id],
                              pick_up_time: ride_params[:return_pick_up_time],
                              reason: @reason,
                              round_trip: false,
                              notes: ride_params[:notes])
    end
    if !return_pick_up_time_not_in_past
      return
    end
    location = save_location_error_handler(@start_location)
    if location.nil?
      flash.now[:error] = @start_location.errors.full_messages.join("\n")
      render 'new'
      return
    else
      @start_location = location
    end
    location = save_location_error_handler(@end_location)
    if location.nil?
      flash.now[:error] = @end_location.errors.full_messages.join("\n")
      render 'new'
      return
    else
      @end_location = location
    end
    @ride.start_location_id = @start_location.id
    @ride.end_location_id = @end_location.id
    round_trip_save
    if !locations_can_not_be_the_same
      return
    end
    when_ride_driver_is_assigned_change_status
    if !@ride.save
      flash.now[:error] = @ride.errors.full_messages.join("\n")
      render 'new'
      return
    else
      return unless round_trip_save
      rider_choose_save_location
      only_15_location_saves(organization)
      if organization.use_tokens == true
        token.ride_id = @ride.id
        token.save
      end
      flash[:notice] = "Ride created for #{rider.full_name}"
      redirect_to admin_ride_path(@ride)
      return
    end
  end

  def update
    @ride = Ride.find(params[:id])
    authorize @ride
    @start_location = @ride.start_location
    @end_location = @ride.end_location
    organization = Organization.find(current_user.organization_id)
    @start_location = Location.new(street: ride_params[:start_street],
                                   city: ride_params[:start_city],
                                   state: ride_params[:start_state],
                                   zip: ride_params[:start_zip])
    location = save_location_error_handler(@start_location)
    if location.nil?
      flash.now[:error] = @start_location.errors.full_messages.join("\n")
      @ride = Ride.find(params[:id])
      render 'edit'
      return
    else
      location = @start_location
    end
    @end_location = Location.new(street: ride_params[:end_street],
                                 city: ride_params[:end_city],
                                 state: ride_params[:end_state],
                                 zip: ride_params[:end_zip])
    location = save_location_error_handler(@end_location)
    if location.nil?
      flash.now[:error] = @end_location.errors.full_messages.join("\n")
      @ride = Ride.find(params[:id])
      render 'edit'
      return
    else
      location = @end_location
    end
    rider_choose_save_location
    only_15_location_saves(organization)
    if @ride.update(
      organization_id: current_user.organization_id,
      rider_id: ride_params[:rider_id],
      driver_id: ride_params[:driver_id],
      pick_up_time: ride_params[:pick_up_time],
      reason: @reason,
      round_trip: ride_params[:round_trip],
      notes: ride_params[:notes],
      start_location: @start_location,
      end_location: @end_location
    )
    else
      render "edit"
      return
    end
    round_trip_false

    if @ride.round_trip
      if @ride.return
        @second_ride = Ride.find(@ride.return)
        @second_ride.update(
          organization_id: current_user.organization_id,
          rider_id: ride_params[:rider_id],
          driver_id: params[:second_ride][:second_driver_id],
          pick_up_time: ride_params[:return_pick_up_time],
          reason: @reason,
          round_trip: false,
          notes: ride_params[:notes],
          start_location: @start_location,
          end_location: @end_location
        )
      else
        @second_ride = Ride.find_or_create_by(organization_id: current_user.organization_id,
                                              rider_id: @ride.rider_id,
                                              driver_id: ride_params[:second_driver_id],
                                              pick_up_time: ride_params[:return_pick_up_time],
                                              reason: @ride.reason,
                                              round_trip: false,
                                              start_location: @start_location,
                                              end_location: @end_location)
      end
      if !return_pick_up_time_not_in_past
        return
      end
      return unless round_trip_save
    end
    if !locations_can_not_be_the_same
      return
    end
    when_ride_driver_is_assigned_change_status
    rider_choose_save_location
    flash.notice = 'The ride information has been updated.'
    redirect_to admin_ride_path(@ride)
  end

  def approve
    @ride = Ride.find(params[:id])
    authorize @ride
    @ride.update_attributes(status: 'approved')
    flash.notice = 'Ride approved.'
    redirect_to request.referrer || admin_ride_index_path
  end

  private

  def ride_params
    params.require(:ride).permit(:rider_id, :driver_id, :pick_up_time, :save_start_location, :save_end_location,
                                 :organization_rider_start_location, :start_street, :start_city, :start_state, :start_zip,
                                 :organization_rider_end_location, :end_street, :end_city, :end_state, :end_zip, :reason,
                                 :status, :q, :round_trip, :second_driver_id, :return_pick_up_time, :notes, :other_reason)
  end

  # TODO: -- possibly clean out old record, and make a plan to fix it in the future.
  def save_location_error_handler(location)
    @old_location = Location.new(street: location.street, city: location.city, state: location.state, zip: location.zip)
    return nil unless location.validate
    if @old_location.street != location.street || @old_location.city != location.city || @old_location.state != location.state || @old_location.zip != location.zip
      flash[:alert] = " We updated the original address you entered: #{@old_location.full_address}. You can see the updated address in the ride details."
    end
    l_new = location.save_or_touch
    l_new
  end


  def when_ride_driver_is_assigned_change_status
    if !@ride.driver_id.nil?
      @ride.status = "scheduled"
    else
      @ride.status = "approved"
    end
    if @ride.round_trip
      if !@second_ride.driver_id.nil?
        @second_ride.status = "scheduled"
      else
        @second_ride.status = "approved"
      end
    else
      return false
    end
  end

  def rider_choose_save_location
    if ride_params[:save_start_location] == 'saved'
      lr1 = LocationRelationship.new(location_id: @ride.start_location.id, organization_id: current_user.organization.id)

app/helpers/admin_ride/cancellation_reasons_helper.rb
module AdminRide::CancellationReasonsHelper
end

app/helpers/admin_ride/ride_cancellations_helper.rb
module AdminRide::RideCancellationsHelper
end

app/helpers/admin_ride_helper.rb
module AdminRideHelper
  
end

app/helpers/ride_cancellations_helper.rb
module RideCancellationsHelper
end

app/views/admin_ride/ride_cancellations/_cancel.html.erb
<div class="d-flex pt-2 pb-2 justify-content-between border-top mr-4 ml-4">
  <% if @ride.id %>
    <% url = cancel_admin_ride_path(@ride) %>
  <% else %>
    <% url = review_admin_ride_path %>
  <% end %>
  <div class="ml-5" style="display: flex; flex-direction: column; flex-wrap: wrap;">
    <div>
      <p>
        <strong>Rider: </strong>
        <%= @ride.rider.full_name %>
      </p>
      <p>
        <strong>Pick up time: </strong>
        <span class="local-time"><%= @ride.pick_up_time.in_time_zone("Eastern Time (US & Canada)").strftime("%A, %b %d, %Y %I:%M %p %Z") %></span>
      </p>
      <p>
        <strong>Status: </strong>
        <%= @ride.status %>
      </p>
      <p>
        <strong>Start Location: </strong>
        <%= @ride.start_location.full_address %>
      </p>
      <p>
        <strong>End Location: </strong>
        <%= @ride.end_location.full_address %>
      </p>
    </div>

    <div>
      <%= link_to 'Back', :back, class: "btn btn-outline-primary" %>
    </div>
  </div>

  <div class="d-flex mr-5 border-left pl-5" style="display: flex; flex-direction: column; flex-wrap: wrap;">
    <%= form_with(url: url , model: @ride, local: true, method: :put) do |form| %>
      <% if @ride.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@ride.errors.count, "error") %> prohibited
            this ride from being saved:
          </h2>
          <ul>
            <% @ride.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="mb-4">
          <%=form.label :cancellation_reason %><br>
          <div class="row">
            <% if Ride::RIDE_CANCELLATION_CATEGORIES.include? form.object.cancellation_reason %>
              <%= form.select :cancellation_reason, Ride.ride_cancellation_categories, selected: 'Other', class: 'p-1' %>
              <%= form.text_field :cancellation_other_reason, value: form.object.cancellation_reason, placeholder: "Detail... "%>
            <%else%>
             <%= form.select :cancellation_reason, Ride.ride_cancellation_categories, selected: form.object.cancellation_reason, class: 'p-1' %>
             <%= form.text_field :cancellation_other_reason, style: 'display:none', placeholder: "Detail... "%>
            <%end%>
          </div>
      </div>
      <div class="mt-5">
        <%= form.submit "Submit", class: "btn btn-warning" %>
      </div>
    <%end%>
  </div>
</div>

<script type="text/javascript">
  // Display ride reason input field only if the Ride cancellation category is 'Other'
  $(document).ready(function(){
    $('#ride_cancellation_reason').on('change', function() {
      if (this.value === 'Other') {
        $("#ride_cancellation_other_reason").show();
      } else {
        $("#ride_cancellation_other_reason").hide();
      }
    });
  });
</script>

app/views/admin_ride/ride_cancellations/_form.html.erb
<div class="d-flex pt-2 pb-2 justify-content-between border-top mr-4 ml-4">
  <% if @ride.id %>
    <% url = cancel_admin_ride_path(@ride) %>
  <% else %>
    <% url = review_admin_ride_path %>
  <% end %>
  <div class="ml-5" style="display: flex; flex-direction: column; flex-wrap: wrap;">
    <div>
      <p>
        <strong>Rider: </strong>
        <%= @ride.rider.full_name %>
      </p>
      <p>
        <strong>Pick up time: </strong>
        <span class="local-time"><%= @ride.pick_up_time %></span>
      </p>
      <p>
        <strong>Status: </strong>
        <%= @ride.status %>
      </p>
      <p>
        <strong>Start Location: </strong>
        <%= @ride.start_location.full_address %>
      </p>
      <p>
        <strong>End Location: </strong>
        <%= @ride.end_location.full_address %>
      </p>
    </div>

    <div>
      <%= link_to 'Back', :back, class: "btn btn-outline-primary" %>
    </div>
  </div>

  <div class="d-flex mr-5 border-left pl-5" style="display: flex; flex-direction: column; flex-wrap: wrap;">
    <%= form_with(url: url , model: @ride, local: true) do |form| %>
      <% if @ride.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@ride.errors.count, "error") %> prohibited
            this ride from being saved:
          </h2>
          <ul>
            <% @ride.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="mb-4">
          <%= form.label :reasons %><br>
          <div class="row">
            <%= form.nested_fields_for :reasons, style: "display: flex" do |ff| %>
             <%= ff.hidden_field :ride_category_id %>

             <%= ff.select :cancellation_category_id, CancellationCategory.where("organization_id =?", current_user.organization_id).order(name: :asc).map {|rc| [ rc.name, rc.id, {'data-cancellation_category_name' => rc.name} ]} %>

             <div style="display:none" class="ride_category-description">
               <%= ff.text_field :details, placeholder: "details" %>
             </div>

             <%= ff.remove_nested_fields_link 'Remove'%>
           <%end %><br/>
          </div>
          <%= form.add_nested_fields_link :reasons %>
      </div>
      <div class="mt-5">
        <%= form.submit "Cancel", class: "btn btn-warning", method: :put %>
      </div>
    <%end%>
  </div>
</div>

app/views/admin_ride/ride_cancellations/review.html.erb
<div class="container admin-ride">
  <h4 style="text-align: center">Cancel Ride</h4>
  <%= render 'cancel' %>
</div>