config/routes.rb
Rails.application.routes.draw do
  devise_for :drivers, path: 'drivers', controllers: {sessions: "drivers/sessions"}

  namespace :admin do
    resources :drivers do
      resources :vehicles, shallow: true
      put :accept
      put :reject
      put :pass
      put :fail
      put :activation
    end
  end

  devise_scope :driver do
    get 'ascending_sort' => 'drivers#ascending_sort'
  end

  devise_for :users, skip: [:registrations],path: 'users', controllers: {sessions: "users/sessions"}
  devise_scope :user do
    resource :users,
             only: [:edit, :update, :destroy],
             controller: 'devise/registrations',
             as: :user_registration do
              get 'cancel'
             end
    get 'user' => "welcome#index"
  end

  resources :organizations, controllers: {registrations: "organizations/registrations"}
  # devise_for :riders, :skip => [:registrations],  path: 'riders', controllers: {sessions: "riders/sessions"}

  resources :riders do
    collection do
      get 'edit/:rider_id' => 'riders#edit'
      post 'bulk_update'
    end
    member do
      get 'locations'
    end
    put :activation
  end
  #
  # devise_scope :rider do
  #   resource :riders_devise,
  #            controller: 'devise/registrations',
  #            as: :rider_registration do
  #             get 'cancel'
  #            end
  #            get 'sort-down' => 'riders#sort_down'
  # end

  mount Api::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"

  get 'welcome/index'
  get 'welcome/welcome'
  get 'welcome/driver'

  get '/privacy_policy' => 'pages#privacy_policy'
  get '/terms_and_conditions' => 'pages#terms_and_conditions'
  get '/support' => 'pages#support'

  resources :rides do
    member do
      put 'cancel' => 'rides#cancel'
    end
  end

  resources :admin_ride do
    member do
      put 'approve' => 'admin_ride#approve'
      get 'review' => 'admin_ride/ride_cancellations#review'
      put 'cancel' => 'admin_ride/ride_cancellations#cancel'
    end
  end

  resources :tokens, path_names: { new: 'new/:rider_id' }

  root 'welcome#welcome'

  namespace :api, :defaults => {:format => :json} do
    as :driver do
      post   "v1/sign-in"       => "v1/sessions#create"
      delete "v1/sign-out"      => "v1/sessions#destroy"
    end
  end

  namespace :user do
    root :to => "welcome#index"
  end

  # namespace :riders do
  #   root :to => "welcome#rider"
  #   resources :tokens
  #
  # end

end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :ride, optional: true
  belongs_to :rider
  before_create :set_expiration_date

  def set_expiration_date
    self.expires_at = Time.now + 30.days
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :authenticate_user!
  layout "administration"

  def show
    @token = Token.find(params[:id])
    authorize @token
  end

  def index
    @tokens = current_user.organization.tokens
    @tokens = Kaminari.paginate_array(@tokens).page(params[:page]).per(10)
  end

  private

  def user_not_authorized
    flash.notice = "You are not authorized to view this information"
    redirect_to tokens_path
  end
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/tokens/_form.html.erb
<%= form_with(model: @token, local: true) do |form| %>


  <% if @token.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@token.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @token.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group offset-md-1 col-md-5">
      <%= form.hidden_field :rider_id %>
    </div>
  </div>

  <div class="row">
    <div class="form-group offset-md-1 col-md-5 ">
      <b><%= form.label :quantity %></b><br>
      <%= form.number_field :quantity, min: 1, class: "form-control" %>
    </div>
    <div  class="form-group col-md-1 offset-md-7">
      <%= form.submit yield(:button_text), class:"btn btn-primary" %>
    </div>
  </div>


<% end %>

app/views/tokens/edit.html.erb
<% provide(:button_text, 'Take') %>
<div class="container">


  <div class="card">

    <h5 class="card-header shadow bg-primary info-color  text-center ">
      <strong class="text-white">Take Tokens</strong>
    </h5><%= render 'form' %>


  </div>
</div>

<%= link_to 'Back To Rider', rider_path(@token.rider_id) %> |
<%= link_to 'Back To Tokens', tokens_path %> |

app/views/tokens/index.html.erb
<div class="container"><br>
  <!-- <h1>Tokens</h1> -->

  <table class="table table-striped">
    <tr class="border-bot">
      <th scope="col">Rider</th>
      <th scope="col">Created at</th>
      <th scope="col">Expiration</th>
      <th scope="col">Used at</th>
      <th scope="col">Validity</th>
    </tr>

    <% @tokens.each do |token| %>
      <% if token.rider.organization_id==current_user.organization_id %>
        <tr>
          <td scope="row"><%= token.rider.full_name %></td>
          <td><%= token.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%b %d, %Y %I:%M %p") unless token.created_at.nil? %></td>
          <td><%= token.expires_at.in_time_zone("Eastern Time (US & Canada)").strftime("%b %d, %Y %I:%M %p") unless token.expires_at.nil? %></td>
          <td><%= token.used_at.in_time_zone("Eastern Time (US & Canada)").strftime("%b %d, %Y %I:%M %p") unless token.used_at.nil? %></td>
          <td><%= t token.is_valid.class %></td>
        </tr>
      <% end %>
    <% end %>
  </table>


  <!-- <link_to edit_rider_path(@rider), class: "btn btn-success new-btn" do %>
    <i class="fa fa-plus"> New Token</i>
  < end %><br/><br/> -->
  <%= paginate @tokens %>
</div>

app/views/tokens/new.html.erb
<% provide(:button_text, 'Give') %>
<div class="container">

  <div class="card">
    <h5 class="card-header shadow bg-primary info-color  text-center ">
      <strong class="text-white">Give Tokens</strong>
    </h5><%= render 'form' %>
  </div>
</div>

<%= link_to 'Back To Rider', rider_path(@token.rider) %> |
<%= link_to 'Back To Tokens', tokens_path %> |

app/views/tokens/show.html.erb
<h4>TOKEN</h4>


<p>
  <strong>Rider ID:</strong>
  <%= @token.rider_id %>
</p>

<p>
  <strong>Created At:</strong>
  <%= @token.created_at %>
</p>


<p>
  <strong>Expires At:</strong>
  <%= @token.expires_at %>
</p>

<p>
  <strong>Used at:</strong>
  <%= @token.used_at %>
</p>

<p>
  <strong>Valid:</strong>
  <%= @token.is_valid%>
</p>



<%= link_to 'Edit', edit_token_path(@token) %> |
<%= link_to 'Back To Rider', rider_path(@token.rider_id) %> |
<%= link_to 'Back To Tokens', tokens_path %> |