config/routes.rb
Rails.application.routes.draw do
  devise_for :drivers, path: 'drivers', controllers: {sessions: "drivers/sessions"}

  namespace :admin do
    resources :drivers do
      resources :vehicles, shallow: true
      put :accept
      put :reject
      put :pass
      put :fail
      put :activation
    end
  end

  devise_scope :driver do
    get 'ascending_sort' => 'drivers#ascending_sort'
  end

  devise_for :users, skip: [:registrations],path: 'users', controllers: {sessions: "users/sessions"}
  devise_scope :user do
    resource :users,
             only: [:edit, :update, :destroy],
             controller: 'devise/registrations',
             as: :user_registration do
              get 'cancel'
             end
    get 'user' => "welcome#index"
  end

  resources :organizations, controllers: {registrations: "organizations/registrations"}
  # devise_for :riders, :skip => [:registrations],  path: 'riders', controllers: {sessions: "riders/sessions"}

  resources :riders do
    collection do
      get 'edit/:rider_id' => 'riders#edit'
      post 'bulk_update'
    end
    member do
      get 'locations'
    end
    put :activation
  end
  #
  # devise_scope :rider do
  #   resource :riders_devise,
  #            controller: 'devise/registrations',
  #            as: :rider_registration do
  #             get 'cancel'
  #            end
  #            get 'sort-down' => 'riders#sort_down'
  # end

  mount Api::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/documentation"

  get 'welcome/index'
  get 'welcome/welcome'
  get 'welcome/driver'

  get '/privacy_policy' => 'pages#privacy_policy'
  get '/terms_and_conditions' => 'pages#terms_and_conditions'
  get '/support' => 'pages#support'

  resources :rides do
    member do
      put 'cancel' => 'rides#cancel'
    end
  end

  resources :admin_ride do
    member do
      put 'approve' => 'admin_ride#approve'
      get 'review' => 'admin_ride/ride_cancellations#review'
      put 'cancel' => 'admin_ride/ride_cancellations#cancel'
    end
  end

  resources :tokens, path_names: { new: 'new/:rider_id' }

  root 'welcome#welcome'

  namespace :api, :defaults => {:format => :json} do
    as :driver do
      post   "v1/sign-in"       => "v1/sessions#create"
      delete "v1/sign-out"      => "v1/sessions#destroy"
    end
  end

  namespace :user do
    root :to => "welcome#index"
  end

  # namespace :riders do
  #   root :to => "welcome#rider"
  #   resources :tokens
  #
  # end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout :resolve_layout
  before_action :current_year_ride_count, only: :index
  before_action :current_day_ride_count, only: :index

  def welcome
    if (current_user)
      redirect_to welcome_index_path
    # else
    #   redirect_to welcome_rider_path
    end
  end

  def rider
    if (current_rider)
      redirect_to rides_path
    end
  end

  def index
    @rides = Ride.where("organization_id =? AND pick_up_time >=?", current_user.organization.id, Date.today).status("pending").order(:pick_up_time)
    @rides = Kaminari.paginate_array(@rides).page(params[:page]).per(5)
    @approved_rides = Ride.where("organization_id =? AND pick_up_time >=?", current_user.organization.id, Date.today).status("approved").order(:pick_up_time)
    @drivers = Driver.where(organization_id: current_user.organization.id).pending.order(:created_at)
    # @rides_completed_this_year = current_year_ride_count
    @drivers = Kaminari.paginate_array(@drivers).page(params[:page]).per(5)
    # @rides_completed_today = current_day_ride_count
    if (!current_user)
      redirect_to welcome_welcome_path
    end
  end

  def driver
    redirect_to welcome_welcome_path
    flash.notice = "Your password has been reset, Please log in on the app."
  end


  private

  def current_year_ride_count
    start_day = Date.today.beginning_of_year
    end_day =  Date.today.end_of_year
    Ride.where("completed_at >= ? AND organization_id = ? AND completed_at <= ? ", start_day, current_user.organization.id, end_day).count
  end

  def current_day_ride_count
    Ride.where(organization_id: current_user.organization.id, status: "completed", completed_at: Date.today).count
  end

  def resolve_layout
    case action_name
    when "rider"
      "rider_layout"
    when "index"
      "administration"
    else
      "application"
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% if current_user.organization.use_rider_app %>
  <div class="container"><br>
    <h5><strong>PENDING RIDES</strong></h5>
    <table class="table table-bordered table-hover contains-times">
      <tr class="border-bot">
        <th scope="col">Rider </th>
        <th scope="col">Driver </th>
        <th scope="col">Pick Up Time </th>
        <th scope="col">Action</th>
      </tr>

      <% @rides.each do |ride| %>
        <tr class="clickable-row" data-href='<%= admin_ride_path(ride) %>'>
          <td class="no-wrap"><%= ride.rider&.full_name %> </td>
          <td class="no-wrap"><%= ride.driver&.full_name %> </td>
          <td class="no-wrap local-time"><%= ride.pick_up_time %></td>
          <td><%= link_to "Approve", approve_admin_ride_path(ride), method: :put  %> |
            <%= link_to "Cancel", review_admin_ride_path(ride), method: :get  %>  </td>
        </tr>
      <% end %>
    </table>
    <%= paginate(@rides) %>
  </div>
<% end %>

<div class="container"><br>
  <h5><strong>APPROVED RIDES</strong></h5>
  <table class="table table-bordered table-hover contains-ties">
    <tr class="border-bot">
      <th scope="col">Rider </th>
      <th scope="col">Driver </th>
      <th scope="col">Pick Up Time </th>
      <th scope="col">Action</th>
    </tr>
    <% @approved_rides.each do |ride| %>
      <tr class="clickable-row" data-href='<%= admin_ride_path(ride) %>'>
        <td class="no-wrap"><%= ride.rider&.full_name %> </td>
        <td class="no-wrap"><%= ride.driver&.full_name %> </td>
        <td class="no-wrap"><%= ride.pick_up_time.in_time_zone("Eastern Time (US & Canada)").strftime("%B %d, %Y %I:%M %p") %></td>
        <td><%= link_to "Cancel", review_admin_ride_path(ride), method: :get %></td>
      </tr>
    <% end %>
  </table>
  <%= paginate(@rides) %>
</div>

<div class="container">
  <h5><strong>COMPLETED RIDES</strong></h5>
  <table class="table table-bordered table-hover">
    <tr class="border-bot">
      <th scope="col">Rides completed this year</th>
      <td><%= @rides_completed_this_year %></td>
      </tr>
    <tr class="border-bot">
      <th scope="col">Rides completed Today</th>
      <td><%= @rides_completed_today %></td>
    </tr>
  </table>
</div>


<div class="container"><br>
  <h5> <strong>PENDING DRIVERS</strong></h5>
  <table class="table table-bordered table-hover">
    <tr style="background-color: #00bcd4;">
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
    </tr>
    <% @drivers.each do |driver| %>
      <% if driver.organization_id == current_user.organization_id%>
        <tr class="clickable-row", data-href='<%= admin_driver_path(driver) %>'>
          <td><%= driver.first_name %></td>
          <td><%= driver.last_name %></td>
          <td><%= number_to_phone(driver.phone) %></td>
          <td><%= driver.email %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
  <%= paginate(@drivers) %>
</div>


<script type="text/javascript">
  jQuery(document).ready(function($) {
      $(".clickable-row").click(function() {
          window.location = $(this).data("href");
      });
      const table = document.querySelector('.contains-times');
      const timeCells = table.querySelectorAll('* .local-time');
      for (let i = 0;i < timeCells.length; i += 1) {
        let timeEntry = timeCells[i].innerHTML.split(" UTC")[0];
        timeEntry = new moment.utc(timeEntry).local();
        timeCells[i].innerHTML=timeEntry.format("LLL");
      }
  });
</script>

app/views/welcome/rider.html.erb
<h1 class="welcome">Welcome <%= current_rider.first_name%>!</h1>

app/views/welcome/welcome.html.erb
<div class="container" id="welcome">
  <h1 class="app-name">CRSN</h1>
  <p class="app-name">Community Ride Share Network</p>

  <div class="login-menu">
      <%= link_to "Login as Admin", new_user_session_path, :class => 'btn btn-success', id: "admin-login" %>
      <!-- < link_to "Login as Rider", new_rider_session_path, :class => 'btn btn-success', id: "rider-login" %> -->
  </div>

</div>